pipeline {
    agent {
        docker { image 'maven:3.9.4-jdk-17' } // Image Maven + JDK 17 existante
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev',
                    url: 'https://github.com/AmalChegdali/Projet-DevOps-AmalChegdali.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -B'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test -B'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }

        stage('Deploy') {
            steps {
                echo 'Déploiement optionnel'
            }
        }
    }

    post {
        success {
            echo "Pipeline terminé avec succès !"
        }
        failure {
            echo "Pipeline échoué !"
        }
    }
}
